version: "3.9"

services:
  redis:
    image: redis:7
    container_name: redis_notification
    ports:
      - "6379:6379"

  http-server:
    build: ./apps/http-server
    container_name: http_server
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  processor:
    build: ./apps/processor
    container_name: processor
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  worker:
    build: ./apps/worker
    container_name: worker
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis